<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1660362355142' stop='1660362415453'>
    <name>My Customer registration</name>
    <title>My Customer registration</title>
    <test-cases>
        <test-case start='1660362355144' status='broken' stop='1660362415451'>
            <name>should register with valid credentials</name>
            <title>should register with valid credentials</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-1'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-104.0.5112.81'/>
            </parameters>
            <steps>
                <step start='1660362355446' status='broken' stop='1660362415451'>
                    <name>POST /session/:sessionId/url</name>
                    <title>POST /session/:sessionId/url</title>
                    <attachments>
                        <attachment title='Request' source='d9a93dbd-d210-4bdf-be4a-399b2ee4977b-attachment.json' type='application/json' size='48'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Timeout of 60000ms exceeded. The execution in the test "My Customer registration should register with valid credentials" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (C:\Users\LENOVO\Desktop\Wdio Scripts\test\specs\setmore_addcustomer.js)</message>
                <stack-trace>Error: Timeout of 60000ms exceeded. The execution in the test "My Customer registration should register with valid credentials" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (C:\Users\LENOVO\Desktop\Wdio Scripts\test\specs\setmore_addcustomer.js)
                    at createTimeoutError (C:\Users\LENOVO\Desktop\Wdio Scripts\node_modules\mocha\lib\errors.js:498:15)
                    at Test.Runnable._timeoutError (C:\Users\LENOVO\Desktop\Wdio Scripts\node_modules\mocha\lib\runnable.js:431:10)
                    at Timeout.&lt;anonymous> (C:\Users\LENOVO\Desktop\Wdio Scripts\node_modules\mocha\lib\runnable.js:246:24)
                    at listOnTimeout (node:internal/timers:559:17)
                    at processTimers (node:internal/timers:502:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>